#### 方法 **T** 对于一、二维数组

In [1]:
import numpy as np

#生成一个[3, 4]的数组
arr = np.arange(12).reshape(3, 4)
print "转置前："
print arr

#求转置
arr_T = arr.T
print "转置后："
print arr_T

转置前：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
转置后：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


#### 高维数组
**对于高维数组，transpose需要用到一个由轴编号组成的元组，才能进行转置**

对多维数组来说，确定最底层的一个基本元素位置需要用到的索引个数即是维度。

比如说三维的数组，那就对维度进行编号，也就是0,1,2。这样说可能比较抽象。这里的0,1,2可以理解为对shape返回元组的索引。


In [2]:
import numpy as np

#生成一个[2, 1, 3]的数组
arr = np.arange(12).reshape(2,2,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

**数组的规模**
[]表示列(维度 1)的个数
[[]]表示行(维度 0)的个数
[[[x1,x2,...,xn]],...,[]]]表示有n个深度(维度 2的个数)

In [3]:
arr.shape

(2, 2, 3)

|形状|索引|
|:-: |:-: |
|2 |0|
|2 |1|
|3 |2|

`transpose`参数的真正意义在于这个`shape`元组的索引。

比如，数值6开始的索引是`[1,0,0]`，变换后变成了`[0,1,0]`。
这也说明了，`transpose`依赖于`shape`。

In [4]:
# (0,1,2) -> (1,0,2)
#[1,2,3]
arr_t1 = arr.transpose(1, 0, 2)
arr_t1

array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])

### **swapaxes**

它接受一对轴编号。进行轴对换。其实也就是shape参数。

In [5]:
arr2 = np.arange(16).reshape(2,2,4)
arr2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [6]:
arr2.shape

(2, 2, 4)

In [7]:
arr2.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [8]:
arr2.swapaxes(1,0)#转置，对比transpose（1,0,2）

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [9]:
arr2.transpose(1,0,2)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [10]:
arr2.shape[-1]

4